package com.ponto_certo.domain.enums;

public enum Itens {
    OLEO_DE_COZINHA,
    PNEUS,
    MEDICAMENTO_DOMICILIAR,
    CAIXAS_E_BULAS_DE_MEDICAMENTO,
    SERINGAS_E_AGULHAS_ACOPLADAS_A_SERINGA_DOMICILIAR,
    PILHAS_E_BATERIAS,
    LAMPADAS,
    TINTA_SOLVENTE_E_VERNIZ,
    ENTULHO_DE_CONSTRUCAO_CIVIL,
    RESIDUO_DE_FOSSA,
    RESIDUO_DE_PODA,
    MOVEIS,
    ELETRODOMESTICOS,
    ELETROELETRONICOS,
    MATERIAIS_RECICLAVEIS,
    EMBALAGENS_DE_VIDRO,
    LIXO_ORGANICO,
    COMPOSTAVEIS
}